(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin
    (begin (load-module "gerbil/expander__rt"))
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin))
  (load-module "gerbil/compiler/base__0"))
