(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin
    (begin
      (load-module "gerbil/expander__rt")
      (load-module "gerbil/compiler/base__rt")
      (load-module "gerbil/compiler/compile__rt")
      (load-module "gerbil/gambit/misc__rt")
      (load-module "gerbil/gambit/ports__rt"))
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin))
  (load-module "gerbil/compiler/driver__0"))
