(declare (block) (standard-bindings) (extended-bindings) (inlining-limit 200))
(begin
  (define |gxc[1]#_g223956_|
    (##structure
     gx#syntax-quote::t
     '::basic-xform
     #f
     (gx#current-expander-context)
     '()))
  (define |gxc[1]#_g223957_|
    (##structure
     gx#syntax-quote::t
     '::optimize-call::t
     #f
     (gx#current-expander-context)
     '()))
  (define |gxc[1]#_g223958_|
    (##structure
     gx#syntax-quote::t
     'make-::optimize-call
     #f
     (gx#current-expander-context)
     '()))
  (define |gxc[1]#_g223959_|
    (##structure
     gx#syntax-quote::t
     '::optimize-call?
     #f
     (gx#current-expander-context)
     '()))
  (define |gxc[1]#_g223960_|
    (##structure
     gx#syntax-quote::t
     '::void
     #f
     (gx#current-expander-context)
     '()))
  (define |gxc[1]#_g223961_|
    (##structure
     gx#syntax-quote::t
     '::check-return-type::t
     #f
     (gx#current-expander-context)
     '()))
  (define |gxc[1]#_g223962_|
    (##structure
     gx#syntax-quote::t
     'make-::check-return-type
     #f
     (gx#current-expander-context)
     '()))
  (define |gxc[1]#_g223963_|
    (##structure
     gx#syntax-quote::t
     '::check-return-type?
     #f
     (gx#current-expander-context)
     '()))
  (begin
    (define |gxc[:0:]#::optimize-call|
      (gerbil/core/mop~MOP-2#make-class-type-info
       'id:
       'gxc#::optimize-call::t
       'name:
       '::optimize-call
       'slots:
       '()
       'ordered-slots:
       '()
       'super:
       (cons |gxc[1]#_g223956_| '())
       'struct?:
       '#f
       'final?:
       '#t
       'metaclass:
       '#f
       'constructor-method:
       '#f
       'type-descriptor:
       |gxc[1]#_g223957_|
       'constructor:
       |gxc[1]#_g223958_|
       'predicate:
       |gxc[1]#_g223959_|
       'accessors:
       '()
       'mutators:
       '()
       'unchecked-accessors:
       '()
       'unchecked-mutators:
       '()
       'slot-types:
       '()
       'slot-contracts:
       '()
       'slot-defaults:
       '()))
    (define |gxc[:0:]#::check-return-type|
      (gerbil/core/mop~MOP-2#make-class-type-info
       'id:
       'gxc#::check-return-type::t
       'name:
       '::check-return-type
       'slots:
       '()
       'ordered-slots:
       '()
       'super:
       (cons |gxc[1]#_g223960_| '())
       'struct?:
       '#f
       'final?:
       '#t
       'metaclass:
       '#f
       'constructor-method:
       '#f
       'type-descriptor:
       |gxc[1]#_g223961_|
       'constructor:
       |gxc[1]#_g223962_|
       'predicate:
       |gxc[1]#_g223963_|
       'accessors:
       '()
       'mutators:
       '()
       'unchecked-accessors:
       '()
       'unchecked-mutators:
       '()
       'slot-types:
       '()
       'slot-contracts:
       '()
       'slot-defaults:
       '()))))
