(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin (load-module "gerbil/compiler/optimize__rt"))
  (begin)
  (begin)
  (begin)
  (begin)
  (begin)
  (begin)
  (begin)
  (begin))
