(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin
    (begin)
    (begin
      (load-module "gerbil/expander/common__rt")
      (load-module "gerbil/expander/stx__rt")
      (load-module "gerbil/expander/core__rt"))
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin))
  (load-module "gerbil/expander/compile__0"))
