;;; -*- Gerbil -*-
;;; © vyzo
;;; reader tests
(import :std/test
        :std/error
        :std/iter
	:std/interface
	:std/serde/interface
	:std/serde/deserialize
        :std/serde/serde-test-support
	./api
	./io
	./reader)
(export reader-test reader-dag-test reader-default-test)

(def reader-test
  (test-suite "read format written objects"
    (test-case "read integers"
      (check (read-object-from-string "1234" (reader-environment))
	     => 1234)
      (check (read-object-from-string "123456789012345678901234567890" (reader-environment))
	     =>  123456789012345678901234567890)
      (check (read-object-from-string "#x1234ab" (reader-environment))
	     => #x1234ab)
      (check (read-object-from-string "#x012345ab" (reader-environment))
	     => #x12345ab)
      (check (read-object-from-string "#x12345ab" (reader-environment))
	     => #x12345ab)
      (check (read-object-from-string "#x1234AB" (reader-environment))
	     => #x1234ab)
      (check (read-object-from-string "#b1001" (reader-environment))
	     => #b1001)
      (check (read-object-from-string "#o1234" (reader-environment))
	     => #o1234))
    (test-case "read flonums"
      (check (read-object-from-string "1." (reader-environment))
	     => 1.)
      (check (read-object-from-string "1.1" (reader-environment))
	     => 1.1)
      (check (read-object-from-string "1.10000" (reader-environment))
	     => 1.1))
    (test-case "read ratnums"
      (check (read-object-from-string "1/3" (reader-environment))
	     => 1/3)
      (check (read-object-from-string "-1/3" (reader-environment))
	     => -1/3))
    (test-case "read cpxnums"
      (check (read-object-from-string "3+i" (reader-environment))
	     => 3+i)
      (check (read-object-from-string "3-i" (reader-environment))
	     => 3-i)
      (check (read-object-from-string "3+2i" (reader-environment))
	     => 3+2i)
      (check (read-object-from-string "3-2i" (reader-environment))
	     => 3-2i)
      (check (read-object-from-string "+i" (reader-environment))
	     => +i)
      (check (read-object-from-string "-i" (reader-environment))
	     => -i))
    (test-case "read special numbers"
      (check (read-object-from-string "+inf.0" (reader-environment))
	     => +inf.0)
      (check (read-object-from-string "-inf.0" (reader-environment))
	     => -inf.0)
      (check (read-object-from-string "+nan.0" (reader-environment))
	     ? nan?)
      (check (read-object-from-string "-nan.0" (reader-environment))
	     ? nan?))
    (test-case "read symbolic"
      (check (read-object-from-string "foo" (reader-environment))
	     => 'foo)
      (check (read-object-from-string "|foo:bar baz|" (reader-environment))
	     => '|foo:bar baz|)
      (check (read-object-from-string "foo:" (reader-environment))
	     => 'foo:)
      (check (read-object-from-string "|foo:bar baz|:" (reader-environment))
	     => '|foo:bar baz|:))
    (test-case "read lists"
      (check (read-object-from-string "(1 2 3)" (reader-environment))
	     => '(1 2 3))
      (check (read-object-from-string "(1 2 3 . 4)" (reader-environment))
	     => '(1 2 3 . 4))
      (let (x [1 . #f])
	(check (read-object-from-string "(1 . #f)" (reader-environment))
	       => x)
	(set-cdr! x x)
	(check (read-object-from-string "#0=(1 . #0#)" (reader-environment))
	       => x)
	(set-cdr! x [2 . x])
	(check (read-object-from-string "#0=(1 2 . #0#)" (reader-environment))
	       => x)
	(set-cdr! x [x . x])
	(check (read-object-from-string "#0=(1 #0# . #0#)" (reader-environment))
	       => x))
      (let ((x [1 . #f])
	    (y [#f . #f]))
	(set-cdr! x x)
	(set-cdr! y y)
	(set-car! y x)
	(check (read-object-from-string "#0=(#1=(1 . #1#) . #0#)" (reader-environment))
	       => y)))
    (test-case "read strings"
      (check (read-object-from-string "\"the quick brown fox\"" (reader-environment))
	     => "the quick brown fox")
      (check (read-object-from-string "\"the quick brown fox\\r\\n\"" (reader-environment))
	     => "the quick brown fox\r\n"))
    (test-case "read vectors"
      (check (read-object-from-string "#(a b c)" (reader-environment))
	     => '#(a b c))
      (let (x (vector #f 'b 'c))
	(vector-set! x 0 x)
	(check (read-object-from-string "#0=#(#0# b c)" (reader-environment))
	       => x))
      (check (read-object-from-string "#[a b c]" (reader-environment))
	     => (values 'a 'b 'c))
      (check (read-object-from-string "#&1" (reader-environment))
	     => '#&1)
      (check (read-object-from-string "#u8(0 1 2 3)" (reader-environment))
	     =>  '#u8(0 1 2 3))
      (check (read-object-from-string "#u16(0 1 2 3)" (reader-environment))
	     => '#u16(0 1 2 3))
      (check (read-object-from-string "#u32(0 1 2 3)" (reader-environment))
	     =>  '#u32(0 1 2 3))
      (check (read-object-from-string "#u64(0 1 2 3)" (reader-environment))
	     =>  '#u64(0 1 2 3))
      (check (read-object-from-string "#s8(0 1 2 3)" (reader-environment))
	     =>  '#s8(0 1 2 3))
      (check (read-object-from-string "#s16(0 1 2 3)" (reader-environment))
	     => '#s16(0 1 2 3))
      (check (read-object-from-string "#s32(0 1 2 3)" (reader-environment))
	     => '#s32(0 1 2 3))
      (check (read-object-from-string "#s64(0 1 2 3)" (reader-environment))
	     =>  '#s64(0 1 2 3))
      (check (read-object-from-string "#f32(0. 1. 2. 3.)" (reader-environment))
	     => '#f32(0.0 1.0 2.0 3.0))
      (check (read-object-from-string "#f64(0. 1. 2. 3.)" (reader-environment))
	     => '#f64(0.0 1.0 2.0 3.0)))
    (test-case "read objects"
      (let ()
	(def b (B x: 2))
	(def a (A b: b))
	(let (obj (read-object-from-string "#{std/serde/serde-test-support#A::t b: #{std/serde/serde-test-support#B::t}}" (reader-environment)))
	  (check obj ? A?)
	  (check (A-b obj) ? B?)
	  (check (B-x (A-b obj)) => 2)))
      (let ()
	(def c (A b: #f))
	(set! (A-b c) c)
	(let (obj (read-object-from-string "#0=#{std/serde/serde-test-support#A::t b: #0#}" (reader-environment)))
	  (check obj ? A?)
	  (check (A-b obj) => obj))))
    (test-case "read interface instances"
      (let (obj (read-object-from-string "#{std/serde/serde-test-support#C::t object: #{std/serde/serde-test-support#A::t b: 1}}" (reader-environment)))
	(check obj ? C?)
	(check (C-foo! obj) => 1)))
    (test-case "read hashes"
      (let (obj (read-object-from-string "#{HashTable::t object: #:{hash-table::t ((b . 2) (a . 1))}}" (reader-environment)))
	(check obj ? HashTable?)
	(check (hash-length obj) => 2)
	(check (hash-ref obj 'a) => 1)
	(check (hash-ref obj 'b) => 2)))
      ))

(def reader-dag-test
  (test-suite "read dag format written objects"
    (test-case "read integers"
      (check (read-object-from-string "1234" (reader-environment dag: #t))
	     => 1234)
      (check (read-object-from-string "123456789012345678901234567890" (reader-environment dag: #t))
	     =>  123456789012345678901234567890)
      (check (read-object-from-string "#x1234ab" (reader-environment dag: #t))
	     => #x1234ab)
      (check (read-object-from-string "#x012345ab" (reader-environment dag: #t))
	     => #x12345ab)
      (check (read-object-from-string "#x12345ab" (reader-environment dag: #t))
	     => #x12345ab)
      (check (read-object-from-string "#x1234AB" (reader-environment dag: #t))
	     => #x1234ab)
      (check (read-object-from-string "#b1001" (reader-environment dag: #t))
	     => #b1001)
      (check (read-object-from-string "#o1234" (reader-environment dag: #t))
	     => #o1234))
    (test-case "read flonums"
      (check (read-object-from-string "1." (reader-environment dag: #t))
	     => 1.)
      (check (read-object-from-string "1.1" (reader-environment dag: #t))
	     => 1.1)
      (check (read-object-from-string "1.10000" (reader-environment dag: #t))
	     => 1.1))
    (test-case "read ratnums"
      (check (read-object-from-string "1/3" (reader-environment dag: #t))
	     => 1/3)
      (check (read-object-from-string "-1/3" (reader-environment dag: #t))
	     => -1/3))
    (test-case "read cpxnums"
      (check (read-object-from-string "3+i" (reader-environment dag: #t))
	     => 3+i)
      (check (read-object-from-string "3-i" (reader-environment dag: #t))
	     => 3-i)
      (check (read-object-from-string "3+2i" (reader-environment dag: #t))
	     => 3+2i)
      (check (read-object-from-string "3-2i" (reader-environment dag: #t))
	     => 3-2i)
      (check (read-object-from-string "+i" (reader-environment dag: #t))
	     => +i)
      (check (read-object-from-string "-i" (reader-environment dag: #t))
	     => -i))
    (test-case "read special numbers"
      (check (read-object-from-string "+inf.0" (reader-environment dag: #t))
	     => +inf.0)
      (check (read-object-from-string "-inf.0" (reader-environment dag: #t))
	     => -inf.0)
      (check (read-object-from-string "+nan.0" (reader-environment dag: #t))
	     ? nan?)
      (check (read-object-from-string "-nan.0" (reader-environment dag: #t))
	     ? nan?))
    (test-case "read symbolic"
      (check (read-object-from-string "foo" (reader-environment dag: #t))
	     => 'foo)
      (check (read-object-from-string "|foo:bar baz|" (reader-environment dag: #t))
	     => '|foo:bar baz|)
      (check (read-object-from-string "foo:" (reader-environment dag: #t))
	     => 'foo:)
      (check (read-object-from-string "|foo:bar baz|:" (reader-environment dag: #t))
	     => '|foo:bar baz|:))
    (test-case "read lists"
      (check (read-object-from-string "(1 2 3)" (reader-environment dag: #t))
	     => '(1 2 3))
      (check (read-object-from-string "(1 2 3 . 4)" (reader-environment dag: #t))
	     => '(1 2 3 . 4))
      (let (x [1 . #f])
	(check (read-object-from-string "(1 . #f)" (reader-environment dag: #t))
	       => x)
	(set-cdr! x x)
	(check-exception (read-object-from-string "#0=(1 . #0#)" (reader-environment dag: #t))
			 ContractViolation?)
	(set-cdr! x [2 . x])
	(check-exception (read-object-from-string "#0=(1 2 . #0#)" (reader-environment dag: #t))
			 ContractViolation?)
	(set-cdr! x [x . x])
	(check-exception (read-object-from-string "#0=(1 #0# . #0#)" (reader-environment dag: #t))
			 ContractViolation?))
      (let ((x [1 . #f])
	    (y [#f . #f]))
	(set-cdr! x x)
	(set-cdr! y y)
	(set-car! y x)
	(check-exception (read-object-from-string "#0=(#1=(1 . #1#) . #0#)" (reader-environment dag: #t))
			 ContractViolation?)))
    (test-case "read strings"
      (check (read-object-from-string "\"the quick brown fox\"" (reader-environment dag: #t))
	     => "the quick brown fox")
      (check (read-object-from-string "\"the quick brown fox\\r\\n\"" (reader-environment dag: #t))
	     => "the quick brown fox\r\n"))
    (test-case "read vectors"
      (check (read-object-from-string "#(a b c)" (reader-environment dag: #t))
	     => '#(a b c))
      (let (x (vector #f 'b 'c))
	(vector-set! x 0 x)
	(check-exception (read-object-from-string "#0=#(#0# b c)" (reader-environment dag: #t))
			 ContractViolation?)
      (check (read-object-from-string "#[a b c]" (reader-environment dag: #t))
	     => (values 'a 'b 'c))
      (check (read-object-from-string "#&1" (reader-environment dag: #t))
	     => '#&1)
      (check (read-object-from-string "#u8(0 1 2 3)" (reader-environment dag: #t))
	     =>  '#u8(0 1 2 3))
      (check (read-object-from-string "#u16(0 1 2 3)" (reader-environment dag: #t))
	     => '#u16(0 1 2 3))
      (check (read-object-from-string "#u32(0 1 2 3)" (reader-environment dag: #t))
	     =>  '#u32(0 1 2 3))
      (check (read-object-from-string "#u64(0 1 2 3)" (reader-environment dag: #t))
	     =>  '#u64(0 1 2 3))
      (check (read-object-from-string "#s8(0 1 2 3)" (reader-environment dag: #t))
	     =>  '#s8(0 1 2 3))
      (check (read-object-from-string "#s16(0 1 2 3)" (reader-environment dag: #t))
	     => '#s16(0 1 2 3))
      (check (read-object-from-string "#s32(0 1 2 3)" (reader-environment dag: #t))
	     => '#s32(0 1 2 3))
      (check (read-object-from-string "#s64(0 1 2 3)" (reader-environment dag: #t))
	     =>  '#s64(0 1 2 3))
      (check (read-object-from-string "#f32(0. 1. 2. 3.)" (reader-environment dag: #t))
	     => '#f32(0.0 1.0 2.0 3.0))
      (check (read-object-from-string "#f64(0. 1. 2. 3.)" (reader-environment dag: #t))
	     => '#f64(0.0 1.0 2.0 3.0)))
    (test-case "read objects"
      (let ()
	(def b (B x: 2))
	(def a (A b: b))
	(check-exception (read-object-from-string "#{std/serde/serde-test-support#A::t b: #{std/serde/serde-test-support#B::t}}" (reader-environment dag: #t))
			 ContractViolation?))
      (let ()
	(def c (A b: #f))
	(set! (A-b c) c)
	(check-exception (read-object-from-string "#0=#{std/serde/serde-test-support#A::t b: #0#}" (reader-environment dag: #t))
			 ContractViolation?))
    (test-case "read interface instances"
      (let (obj (read-object-from-string "#{std/serde/serde-test-support#C::t object: #{std/serde/serde-test-support#A::t b: 1}}" (reader-environment dag: #t)))
	(check obj ? C?)
	(check (C-foo! obj) => 1)))
    (test-case "read hashes"
      (let (obj (read-object-from-string "#{HashTable::t object: #:{hash-table::t ((b . 2) (a . 1))}}" (reader-environment dag: #t)))
	(check obj ? HashTable?)
	(check (hash-length obj) => 2)
	(check (hash-ref obj 'a) => 1)
	(check (hash-ref obj 'b) => 2)))
    ))))

(def reader-default-test
  (test-suite "reader default environment"
    (test-case "read cycles"
      (let (x [1 . #f])
	(check (read-object-from-string "(1 . #f)")
	       => x)
	(set-cdr! x x)
	(check (read-object-from-string "#0=(1 . #0#)")
	       => x)
	(set-cdr! x [2 . x])
	(check (read-object-from-string "#0=(1 2 . #0#)")
	       => x)
	(set-cdr! x [x . x])
	(check (read-object-from-string "#0=(1 #0# . #0#)")
	       => x)))))
