(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin
    (begin)
    (begin (load-module "gerbil/gambit/hvectors__rt"))
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin)
    (begin))
  (load-module "gerbil/gambit/ports__0"))
