#!/bin/sh
set -eu


if [ -z "${GERBIL_HOME:-}" ]; then
    SCRIPT=$(readlink --canonicalize "$0")
    GERBIL_HOME=$(dirname "${SCRIPT%/*}")
    export GERBIL_HOME
fi


if [ $# -gt 0 ]; then
    case $1 in
        --home)
            echo -n $GERBIL_HOME;
            exit 0;
            ;;
    esac
fi

if [ $# -gt 0 ]; then
    case $1 in
        -:*)
            GSIOPTIONS=$1
            shift
            ;;
    esac
fi

if [ $# -gt 0 ]; then
    case $1 in
        --lang)
            export GERBIL_LANG=$2
            shift 2
            ;;
    esac
fi

if [ $# -eq 0 ]; then
    exec gsi ${GSIOPTIONS:-} $GERBIL_HOME/lib/gxi-init $GERBIL_HOME/lib/gxi-interactive -
else
    exec gsi ${GSIOPTIONS:-} $GERBIL_HOME/lib/gxi-init "$@"
fi
