#!/usr/bin/env bash
set -eu

if [ -z "${GERBIL_HOME:-}" ]; then
    GERBIL_HOME=$(dirname $(cd ${0%/*} && echo $PWD))
    export GERBIL_HOME
fi

if [ $# -gt 0 ]; then
    case $1 in
        -:*)
            GSIOPTIONS=$1
            shift
            ;;
    esac
fi

if [[ "x" = "x$@" ]]; then
    exec gsi ${GSIOPTIONS:-}  -e '(include "~~lib/_gambit#.scm")' $GERBIL_HOME/lib/gxi-init $GERBIL_HOME/lib/gxi-interactive -
else
    exec gsi ${GSIOPTIONS:-} -e '(include "~~lib/_gambit#.scm")' $GERBIL_HOME/lib/gxi-init "$@"
fi
