(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin)
  (begin)
  (begin)
  (begin)
  (begin)
  (begin)
  (begin (load-module "gerbil/core::<runtime>__rt"))
  (begin)
  (begin)
  (begin)
  (begin)
  (begin)
  (begin (load-module "gerbil/core::<sugar>__rt"))
  (begin)
  (begin (load-module "gerbil/core::<MOP>__rt"))
  (begin)
  (begin (load-module "gerbil/core::<match>__rt"))
  (begin)
  (begin (load-module "gerbil/core::<more-sugar>__rt"))
  (begin)
  (begin)
  (begin)
  (begin (load-module "gerbil/core::<module-sugar>__rt")))
