(declare (block) (standard-bindings) (extended-bindings))
(begin
  (load-module "gerbil/core$_runtime___rt")
  (load-module "gerbil/core$_sugar___rt")
  (load-module "gerbil/core$_MOP___rt")
  (load-module "gerbil/core$_match___rt")
  (load-module "gerbil/core$_more-sugar___rt")
  (load-module "gerbil/core$_more-sugar___rt")
  (load-module "gerbil/core$_module-sugar___rt")
  (load-module "gerbil/core$_special___rt"))
