(declare (block) (standard-bindings) (extended-bindings))
(begin
  (load-module "gerbil/expander/common__rt")
  (load-module "gerbil/expander/stx__rt")
  (load-module "gerbil/expander/core__rt")
  (load-module "gerbil/expander/top__rt")
  (load-module "gerbil/expander/module__rt")
  (load-module "gerbil/expander/compile__rt")
  (load-module "gerbil/expander/root__rt")
  (load-module "gerbil/expander/stxcase__rt"))
