(declare (block) (standard-bindings) (extended-bindings))
(begin
  (load-module "gerbil/gambit/threads__rt")
  (load-module "gerbil/gambit/continuations__rt")
  (load-module "gerbil/gambit/bits__rt")
  (load-module "gerbil/gambit/fixnum__rt")
  (load-module "gerbil/gambit/flonum__rt")
  (load-module "gerbil/gambit/random__rt")
  (load-module "gerbil/gambit/hvectors__rt")
  (load-module "gerbil/gambit/ports__rt")
  (load-module "gerbil/gambit/bytes__rt")
  (load-module "gerbil/gambit/readtables__rt")
  (load-module "gerbil/gambit/hash__rt")
  (load-module "gerbil/gambit/exceptions__rt")
  (load-module "gerbil/gambit/os__rt")
  (load-module "gerbil/gambit/system__rt")
  (load-module "gerbil/gambit/foreign__rt")
  (load-module "gerbil/gambit/misc__rt")
  (load-module "gerbil/gambit/exact__rt"))
