(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin
    (load-module "gerbil/runtime/util")
    (load-module "gerbil/runtime/table")
    (load-module "gerbil/runtime/control")
    (load-module "gerbil/runtime/system")
    (load-module "gerbil/runtime/c3")
    (load-module "gerbil/runtime/mop")
    (load-module "gerbil/runtime/error")
    (load-module "gerbil/runtime/interface")
    (load-module "gerbil/runtime/hash")
    (load-module "gerbil/runtime/thread")
    (load-module "gerbil/runtime/syntax")
    (load-module "gerbil/runtime/eval")
    (load-module "gerbil/runtime/repl")
    (load-module "gerbil/runtime/loader")
    (load-module "gerbil/runtime/init"))
  (load-module "gerbil/runtime~0"))
