(import :std/io)
(export #t)

(interface (SMTP Socket)
 (send-mail return-path forward-path . data)
 (send-command cmd)
 (read-all) (read-lines) (keywords)
 (socket) (reader) (writer)
 (EHLO domain-or-address)
 (HELO domain)
 (MAIL from)
 (RCPT to)
 (DATA)
 (RSET)
 (NOOP (str ""))
 (QUIT)
 (VRFY address)
 (STARTTLS))
