(declare (block) (standard-bindings) (extended-bindings))
(begin
  (load-module "gerbil/core/runtime")
  (load-module "gerbil/core/sugar")
  (load-module "gerbil/core/mop")
  (load-module "gerbil/core/match")
  (load-module "gerbil/core/more-sugar")
  (load-module "gerbil/core/module-sugar")
  (load-module "gerbil/core/contract~TypeReference")
  (load-module "gerbil/core/contract~TypeCast")
  (load-module "gerbil/core/contract~Using")
  (load-module "gerbil/core/contract~ContractRules")
  (load-module "gerbil/core/contract~Interface")
  (load-module "gerbil/core/contract~TypedDefinitions"))
