(export evector-test)

(import
  :std/test
  ./evector)

(def evector-test
  (test-suite "test suite for std/vector/evector"
    (test-case "evector"
      (def e (list->evector '(a b c d)))
      (check (evector? e) => #t)
      (check (evector-ref e 0) => 'a)
      (check (evector-push! e 'x 'z #f) => #f)
      (check (evector-push! e 'x 'z) => 4)
      (check (evector-ref e 1) => 'b)
      (check (evector-ref e 2) => 'c)
      (check (evector-ref e 3) => 'd)
      (check (evector-ref e 4) => 'x)
      (check (evector-extend! e 10 'z) => (void))
      (check (evector-set! e 7 'y) => (void))
      (check (evector->vector e) => #(a b c d x))
      (check (evector-fill-pointer-set! e 9) => 9)
      (check (evector->vector e) => #(a b c d x z z y z)))
    (test-case "eu8vector"
      (def e (string->eu8vector "abcd"))
      (check (eu8vector? e) => #t)
      (check (eu8vector-ref e 0) => 97)
      (check (eu8vector-push! e 120 0 #f) => #f)
      (check (eu8vector-push! e 120) => 4)
      (check (eu8vector-ref e 1) => 98)
      (check (eu8vector-ref e 2) => 99)
      (check (eu8vector-ref e 3) => 100)
      (check (eu8vector-ref e 4) => 120)
      (check (eu8vector->u8vector e) => #u8(97 98 99 100 120)))
    (test-case "ebits"
      (def e (bits->ebits #xAC 11))
      (check (ebits? e) => #t)
      (check (map (cut ebits-ref e <>) (iota 11)) => [0 0 1 1 0 1 0 1 0 0 0])
      (check (map (cut ebits-set? e <>) (iota 11)) => [#f #f #t #t #f #t #f #t #f #f #f])
      (check (ebits-push! e 1) => 11)
      (check (ebits-push! e 0) => 12)
      (check (ebits-push! e 1) => 13)
      (check (ebits-push! e 0) => 14)
      (check (ebits-push! e 0) => 15)
      (check (ebits-push! e 0 0 #f) => #f)
      (check (ebits-push! e 0) => 16)
      (check (ebits-push! e 1) => 17)
      (check (ebits-push! e 0) => 18)
      (check (ebits-push! e 1) => 19)
      (check (ebits-push! e 0) => 20)
      (check (ebits-push! e 0) => 21)
      (check (ebits-push! e 1) => 22)
      (check (ebits-fill-pointer-set! e 22) => 22)
      (check (ebits->bits e) => 665772))))
