(export extensible-test)

(import
  :std/test
  ./extensible)

(def extensible-test
  (test-suite "test suite for std/vector/extensible"
    (test-case "ExtensibleVector"
      (def e (list->ExtensibleVector '(a b c d)))
      (check (ExtensibleVector? e) => #t)
      (check (ExtensibleVector-ref e 0) => 'a)
      (check (ExtensibleVector-push! e 'x 'z #f) => #f)
      (check (ExtensibleVector-push! e 'x 'z) => 4)
      (check (ExtensibleVector-ref e 1) => 'b)
      (check (ExtensibleVector-ref e 2) => 'c)
      (check (ExtensibleVector-ref e 3) => 'd)
      (check (ExtensibleVector-ref e 4) => 'x)
      (check (ExtensibleVector-extend! e 10 'z) => (void))
      (check (ExtensibleVector-set! e 7 'y) => (void))
      (check (ExtensibleVector->vector e) => #(a b c d x))
      (check (ExtensibleVector-fill-pointer-set! e 9) => 9)
      (check (ExtensibleVector->vector e) => #(a b c d x z z y z)))
    (test-case "ExtensibleU8Vector"
      (def e (string->ExtensibleU8Vector "abcd"))
      (check (ExtensibleU8Vector? e) => #t)
      (check (ExtensibleU8Vector-ref e 0) => 97)
      (check (ExtensibleU8Vector-push! e 120 0 #f) => #f)
      (check (ExtensibleU8Vector-push! e 120) => 4)
      (check (ExtensibleU8Vector-ref e 1) => 98)
      (check (ExtensibleU8Vector-ref e 2) => 99)
      (check (ExtensibleU8Vector-ref e 3) => 100)
      (check (ExtensibleU8Vector-ref e 4) => 120)
      (check (ExtensibleU8Vector->u8vector e) => #u8(97 98 99 100 120)))
    (test-case "ExtensibleBitVector"
      (def e (bits->ExtensibleBitVector #xAC 11))
      (check (ExtensibleBitVector? e) => #t)
      (check (map (cut ExtensibleBitVector-ref e <>) (iota 11)) => [0 0 1 1 0 1 0 1 0 0 0])
      (check (map (cut ExtensibleBitVector-set? e <>) (iota 11)) => [#f #f #t #t #f #t #f #t #f #f #f])
      (check (ExtensibleBitVector-push! e 1) => 11)
      (check (ExtensibleBitVector-push! e 0) => 12)
      (check (ExtensibleBitVector-push! e 1) => 13)
      (check (ExtensibleBitVector-push! e 0) => 14)
      (check (ExtensibleBitVector-push! e 0) => 15)
      (check (ExtensibleBitVector-push! e 0 0 #f) => #f)
      (check (ExtensibleBitVector-push! e 0) => 16)
      (check (ExtensibleBitVector-push! e 1) => 17)
      (check (ExtensibleBitVector-push! e 0) => 18)
      (check (ExtensibleBitVector-push! e 1) => 19)
      (check (ExtensibleBitVector-push! e 0) => 20)
      (check (ExtensibleBitVector-push! e 0) => 21)
      (check (ExtensibleBitVector-push! e 1) => 22)
      (check (ExtensibleBitVector-fill-pointer-set! e 22) => 22)
      (check (ExtensibleBitVector->bits e) => 665772))))
