(import
  :std/swank/api
  :std/swank/message
  :std/swank/context
  :std/swank/presentation
  :std/swank/eval
  :std/swank/top
  :std/swank/completions
  :std/swank/autodoc
  :std/swank/handlers
  :std/swank/server)
(export
  (import:
   :std/swank/api
   :std/swank/message
   :std/swank/context
   :std/swank/presentation
   :std/swank/eval
   :std/swank/top
   :std/swank/completions
   :std/swank/autodoc
   :std/swank/handlers
   :std/swank/server))