%YAML 1.1
---
name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: vyzo/gerbil

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: cd docker && make
  # test:
  #   runs-on: alpine-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Test the Docker image
  #       run:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: alpine-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: gerbil
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
